config/routes.rb
Rails.application.routes.draw do
  get 'blog/index'
  get 'about/index'
  get 'resume/index'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/blog/index.html.erb
<h1>Blog#index</h1>
<p>Find me in app/views/blog/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "portfolio", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <% if content_for?(:head) %>
      <%= yield(:head) %>
    <% end %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resume/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "resume", "data-turbo-track": "reload" %>
<% end %>

<div class="resume py-5 px-3">
  <div class="my-info">
    <h2>Raymond Hughes</h2>
    <hr>
    <strong>2457 sw washington street, Port Saint Lucie, Florida</strong> <br>
    <strong>772-233-6018</strong> <br>
    <strong>raymond.hughes@live.com</strong>
  </div>

  <div class="summary mt-3">
    <h2>Summary</h2>
    <hr>
    <ul>
      <li>Lead Developer with 8 years of experience</li>
      <li>Bachelors Degree in Software Engineering</li>
      <li>Ruby on Rails experience working on legacy Ruby 1.8.7 through Ruby 3.1 and Rails 2.4 through Rails 7.1</li>
      <li>Experience with PostgreSQL and and Microsoft SQL</li>
      <li>Ran scrum meetings and managed tickets using Epics and Stories</li>
      <li>Experience with Medical based SAAS products that are ONC certified</li>
    </ul>
  </div>

  <div class="experience mt-3">
      <h2>Experience</h2>
      <hr>
    <section>
      <strong>CarePaths Inc. | Port Saint Lucie, Florida</strong> <br>
      <strong>Lead Developer | 05/2016 - Present</strong> <br>

      <p>
        Lead developer for our main cloud EHR product, eRecord. I was responsible for updates and bug fixes. I had a
        multitude of tasks that I was responsible for.
      </p>

      <p>
        Some of the technologies I used and gained years of experience with; Ruby on Rails, ASP, Java, C#, NodeJS, VueJS,
        JavaScript, JSON, R, WebRTC, PSQL, MSQL, and API Development.
      </p>

      <p>
        I headed up the upgrade process from a legacy version of Ruby to an updated version. Made decisions on processes
        and different ways that would streamline the data migration from Microsoft SQL to PostgreSQL 15.
      </p>

      <p>
        I was lead dev on the ONC certifications all of which were passed and CarePaths currently has the latest G10 certification
        for 2022. Helped to design and build the FHIR API for ONC certification.
      </p>

      <p>
        We used TDD and I am familiar with Minitest as well as Cypress integration testing frameworks. I helped to get to a
        76% code coverage from an 8% code coverage.
      </p>

      <p>
        I led the team to integrate WebRTC into our stack using Janus and integrating it into our VueJS frontend.
      </p>

      <p>
        I led the team when we integrated Faxing in app using WKHTMLTOPDF for processing PDFs and Hylafax fax server. I wrote the frontend and backend services to accommodate this change for our clients.
      </p>
    </section>

    <section>
      <strong>A1 Roof Truss | Port Saint Lucie, Florida</strong> <br>
      <strong>Jr Software Developer/IT Intern | 11/2014 - 11/2015</strong> <br>

      <p>
        Worked closely with design teams to develop software that controlled automated saw mechanisms. Helped develop a
        proprietary application, Viper. Assisted the IT director in processes including Active Directory management, Computer
        Upgrades/Builds, and other internal processes that was required by management.
      </p>

      <p>
        This was a one year internship that I attended directly out of college. I successfully completed my duties and was
        able to take what I learned here to further my education within the field of software development.
      </p>
    </section>
  </div>

  <div class="skills">
    <h2>Skills</h2>
    <hr>
    <section>
      <ul>
        <li>Ruby on Rails</li>
        <li>ASP.net</li>
        <li>Microsoft SQL</li>
        <li>Postgresql</li>
        <li>Nodejs</li>
        <li>Elixir</li>
        <li>Minitest</li>
        <li>Computer literacy</li>
        <li>Time management</li>
        <li>Microsoft excel</li>
        <li>Documentation review</li>
        <li>Microsoft word</li>
        <li>Leadership</li>
        <li>Time management</li>
        <li>Communication skills</li>
        <li>Active Directory</li>
      </ul>
    </section>
  </div>

  <div class="education">
    <h2>Education</h2>
    <hr>
    <section>
      <strong>Keiser University. | Port Saint Lucie, Florida</strong> <br>
      <strong>Software Engineering | 01/2012 - 01/2016</strong> <br>

      <ul>
        <li>Graduated summa cum laude—3.7+ GPA</li>
        <li>Majored In Software Engineering</li>
        <li>Used a variety of languages including Java and C#</li>
        <li>Completed my capstone project - Student Nurse time tracker which was used by our campus through all of 2016</li>
        <li>Received Pell Grants for my GPA</li>
        <li>Received a Grant from A1 Roof Truss while attending my internship</li>
      </ul>
    </section>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="border-top bg-dark mt-auto">
  <div class="container d-flex flex-wrap justify-content-between align-items-center">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-muted">Raymond Hughes</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3">
        <a class="text-light" href="https://www.linkedin.com/in/raymond-hughes-13838369/" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
          </svg>
        </a>
      </li>
      <li class="ms-3">
        <a class="text-light" href="https://github.com/Ray-Hughes" target="_blank">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
            <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
          </svg>
        </a>
      </li>
    </ul>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container">
    <%= link_to "Raymond Hughes", root_path, class: "navbar-brand text-light" %>
    <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link text-light", aria: { current: "page" } %>
        </li>
        <li class="nav-item">
          <%= link_to "Resume", resume_index_path, class: "nav-link text-light", aria: { current: "false" } %>
        </li>
        <li class="nav-item">
          <%# link_to "About", about_index_path, class: "nav-link text-light", aria: { current: "false" } %>
        </li>
        <li class="nav-item">
          <%# link_to "Blog", blog_index_path, class: "nav-link text-light", aria: { current: "false" } %>
        </li>
      </ul>
    </div>
  </div>
</nav>